export const categories = [
  "Productivity",
  "Marketing",
  "Finance",
  "Healthcare",
  "Education",
  "Entertainment",
  "Legal",
  "E-commerce",
  "Customer Support",
];

export const agentsData = [
  {
    id: "1",
    name: "CopyMaster",
    description: "AI agent for generating marketing copy and emails.",
    categories: ["Marketing", "Productivity"],
    price: 19.99,
    rating: 4.7,
    reviews: 120,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=400&h=400&fit=crop",
    tags: ["copywriting", "email", "marketing"],
  },
  {
    id: "2",
    name: "FinBot",
    description: "Automate financial reports and analytics.",
    categories: ["Finance", "Productivity"],
    price: 29.99,
    rating: 4.5,
    reviews: 85,
    image: "https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&w=400&h=400&fit=crop",
    tags: ["finance", "analytics", "automation"],
  },
  {
    id: "3",
    name: "EduTutor",
    description: "Personalized AI tutor for students.",
    categories: ["Education"],
    price: 14.99,
    rating: 4.8,
    reviews: 200,
    image: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&w=400&h=400&fit=crop",
    tags: ["education", "tutor", "learning"],
  },
  {
    id: "4",
    name: "MediCare AI",
    description: "Assists with diagnostics and health monitoring.",
    categories: ["Healthcare"],
    price: 49.99,
    rating: 4.6,
    reviews: 60,
    image: "https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg?auto=compress&w=400&h=400&fit=crop",
    tags: ["healthcare", "diagnostics", "monitoring"],
  },
  {
    id: "5",
    name: "LegalEase",
    description: "AI agent for legal advice and document analysis.",
    categories: ["Legal"],
    price: 39.99,
    rating: 4.4,
    reviews: 40,
    image: "https://images.pexels.com/photos/4427612/pexels-photo-4427612.jpeg?auto=compress&w=400&h=400&fit=crop",
    tags: ["legal", "documents", "advice"],
  },
  {
    id: "6",
    name: "ShopSmart",
    description: "Boost sales with AI recommendations for e-commerce.",
    categories: ["E-commerce", "Marketing"],
    price: 24.99,
    rating: 4.9,
    reviews: 150,
    image: "https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&w=400&h=400&fit=crop",
    tags: ["e-commerce", "recommendation", "sales"],
  },
  {
    id: "7",
    name: "SupportGenie",
    description: "Automate customer support with an AI chatbot.",
    categories: ["Customer Support"],
    price: 17.99,
    rating: 4.3,
    reviews: 70,
    image: "https://images.pexels.com/photos/2102416/pexels-photo-2102416.jpeg?auto=compress&w=400&h=400&fit=crop",
    tags: ["support", "chatbot", "automation"],
  },
  {
    id: "8",
    name: "EntertainMe",
    description: "AI agent for personalized movie and music recommendations.",
    categories: ["Entertainment"],
    price: 9.99,
    rating: 4.2,
    reviews: 55,
    image: "https://images.pexels.com/photos/713149/pexels-photo-713149.jpeg?auto=compress&w=400&h=400&fit=crop",
    tags: ["entertainment", "recommendation", "music", "movies"],
  },
];